### ISSUE TITLE
Appium is throwing error of SECURITY

### ISSUE THREAD

**Issue by hansbirkaur** [shahnawazm786/appiumLearningProject#3]
[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.22.3
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"alwaysMatch":{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1674178327913 (20:32:07 GMT-0500 (Eastern Standard Time))
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m 
[info] [35m[Appium][39m Appium v1.22.3 creating new AndroidUiautomator2Driver (v1.70.1) session
[info] [35m[Appium][39m Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "Android",
[debug] [35m[BaseDriver][39m     "appium:udid": "jzz57xbqcqtw7xi7",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "11",
[debug] [35m[BaseDriver][39m     "appium:noReset": false,
[debug] [35m[BaseDriver][39m     "appium:ensureWebviewsHavePages": true,
[debug] [35m[BaseDriver][39m     "appium:nativeWebScreenshot": true,
[debug] [35m[BaseDriver][39m     "appium:newCommandTimeout": 3600,
[debug] [35m[BaseDriver][39m     "appium:connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: d68658ec-8783-4267-b633-f3379079a47f
[info] [35m[UiAutomator2][39m Neither 'app' nor 'appPackage' was set. Starting UiAutomator2 without the target application[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"alwaysMatch":{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"appium:udid":"jzz57xbqcqtw7xi7","platformName":"Android","appium:platformVersion":"11","appium:noReset":false,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1674178327913 (20:32:07 GMT-0500 (Eastern Standard Time))
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m 
[info] [35m[Appium][39m Appium v1.22.3 creating new AndroidUiautomator2Driver (v1.70.1) session
[info] [35m[Appium][39m Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "Android",
[debug] [35m[BaseDriver][39m     "appium:udid": "jzz57xbqcqtw7xi7",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "11",
[debug] [35m[BaseDriver][39m     "appium:noReset": false,
[debug] [35m[BaseDriver][39m     "appium:ensureWebviewsHavePages": true,
[debug] [35m[BaseDriver][39m     "appium:nativeWebScreenshot": true,
[debug] [35m[BaseDriver][39m     "appium:newCommandTimeout": 3600,
[debug] [35m[BaseDriver][39m     "appium:connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: d68658ec-8783-4267-b633-f3379079a47f
[info] [35m[UiAutomator2][39m Neither 'app' nor 'appPackage' was set. Starting UiAutomator2 without the target application
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Android\android-sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'C:\Android\android-sdk\platform-tools\adb.exe -P 5037 start-server'[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices[debug] [35m[ADB][39m Connected devices: [{"udid":"jzz57xbqcqtw7xi7","state":"device"}]
[info] [35m[AndroidDriver][39m Using device: jzz57xbqcqtw7xi7
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Android\android-sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'C:\Android\android-sdk\platform-tools\adb.exe -P 5037 start-server'[debug] [35m[ADB][39m Setting device id to jzz57xbqcqtw7xi7
[debug] [35m[ADB][39m Running 'C:\Android\android-sdk\platform-tools\adb.exe -P 5037 -s jzz57xbqcqtw7xi7 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 30
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Android\android-sdk\platform-tools\adb.exe -P 5037 -s jzz57xbqcqtw7xi7 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 11
[debug] [35m[ADB][39m Device API level: 30
[info] [35m[UiAutomator2][39m Relaxing hidden api policy
[debug] [35m[ADB][39m Running 'C:\Android\android-sdk\platform-tools\adb.exe -P 5037 -s jzz57xbqcqtw7xi7 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[info] [35m[UiAutomator2][39m Restoring hidden api policy to the device default configuration
[debug] [35m[ADB][39m Running 'C:\Android\android-sdk\platform-tools\adb.exe -P 5037 -s jzz57xbqcqtw7xi7 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1674178332213 (20:32:12 GMT-0500 (Eastern Standard Time))
[debug] [35m[W3C][39m Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\Android\\android-sdk\\platform-tools\\adb.exe -P 5037 -s jzz57xbqcqtw7xi7 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output: 
[debug] [35m[W3C][39m Exception occurred while executing 'delete':
[debug] [35m[W3C][39m java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2105)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1291)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1283)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1254)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:458)
[debug] [35m[W3C][39m 	at android.content.ContentProvider.call(ContentProvider.java:2471)
[debug] [35m[W3C][39m 	at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
[debug] [35m[W3C][39m 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
[debug] [35m[W3C][39m 	at android.os.ShellCommand.exec(ShellCommand.java:44)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
[debug] [35m[W3C][39m 	at android.os.Binder.shellCommand(Binder.java:929)
[debug] [35m[W3C][39m 	at android.os.Binder.onTransact(Binder.java:813)
[debug] [35m[W3C][39m 	at android.os.Binder.execTransactInternal(Binder.java:1159)
[debug] [35m[W3C][39m 	at android.os.Binder.execTransact(Binder.java:1123)
[debug] [35m[W3C][39m 
[debug] [35m[W3C][39m Exception occurred while executing 'delete':
[debug] [35m[W3C][39m java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2105)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1291)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1283)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1254)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:458)
[debug] [35m[W3C][39m 	at android.content.ContentProvider.call(ContentProvider.java:2471)
[debug] [35m[W3C][39m 	at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
[debug] [35m[W3C][39m 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
[debug] [35m[W3C][39m 	at android.os.ShellCommand.exec(ShellCommand.java:44)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
[debug] [35m[W3C][39m 	at android.os.Binder.shellCommand(Binder.java:929)
[debug] [35m[W3C][39m 	at android.os.Binder.onTransact(Binder.java:813)
[debug] [35m[W3C][39m 	at android.os.Binder.execTransactInternal(Binder.java:1159)
[debug] [35m[W3C][39m 	at android.os.Binder.execTransact(Binder.java:1123)
[debug] [35m[W3C][39m 
[debug] [35m[W3C][39m Exception occurred while executing 'delete':
[debug] [35m[W3C][39m java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2105)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1291)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1283)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1254)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:458)
[debug] [35m[W3C][39m 	at android.content.ContentProvider.call(ContentProvider.java:2471)
[debug] [35m[W3C][39m 	at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
[debug] [35m[W3C][39m 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
[debug] [35m[W3C][39m 	at android.os.ShellCommand.exec(ShellCommand.java:44)
[debug] [35m[W3C][39m 	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
[debug] [35m[W3C][39m 	at android.os.Binder.shellCommand(Binder.java:929)
[debug] [35m[W3C][39m 	at android.os.Binder.onTransact(Binder.java:813)
[debug] [35m[W3C][39m 	at android.os.Binder.execTransactInternal(Binder.java:1159)
[debug] [35m[W3C][39m 	at android.os.Binder.execTransact(Binder.java:1123)
[debug] [35m[W3C][39m 
[debug] [35m[W3C][39m Error: Command 'C:\\Android\\android-sdk\\platform-tools\\adb.exe -P 5037 -s jzz57xbqcqtw7xi7 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255
[debug] [35m[W3C][39m     at ChildProcess.<anonymous> (C:\Users\simmi\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [35m[W3C][39m     at ChildProcess.emit (events.js:310:20)
[debug] [35m[W3C][39m     at maybeClose (internal/child_process.js:1021:16)
[debug] [35m[W3C][39m     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m4313 ms - 10397[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by hansbirkaur** [comment]
![image](https://user-images.githubusercontent.com/121248404/213601262-af497056-3ea8-49aa-8963-cbeaa86225a6.png)
